### ISSUE TITLE
warning: Using the last argument as keyword parameters is deprecated

### ISSUE THREAD

**Issue by atagunay** [7urkm3n/pcloud#27]
rails 7, ruby 2.72 

1. Add gem 'pcloud' to the gemfile
2. run rails s
3. You see error with this message: Using the last argument as keyword parameters is deprecated

**Comment by 7urkm3n** [comment]
Its fixed, since the json gem was updated had some issues with arguments. Now PCLOUD uses <2.3 ruby

> ./rvm/gems/ruby-2.7.2/gems/json-2.2.0/lib/json/common.rb:156: warning: Using the last argument as keyword parameters is deprecated
