### ISSUE TITLE
wrong number of arguments (given 2, expected 1) (ArgumentError)

### ISSUE THREAD

**Issue by atagunay** [7urkm3n/pcloud#28]
Rails 7, ruby 3.1.2

1.) add gem 'pcloud' to the gemfile
2.) rails s
3.) wrong number of arguments (given 2, expected 1) (ArgumentError)

**Comment by 7urkm3n** [comment]
I will take look later today, Thanks for the Ruby3 issue. I have not tested on Ruby3 yet.

**Comment by atagunay** [comment]
thank you :)

**Comment by 7urkm3n** [comment]
This issue fixed

https://github.com/7urkm3n/pcloud/releases/tag/v0.3.4
